ImitationModel = ['Basic','Multimodal','Codevilla18','Codevilla19','Kim2017','Experimental','ExpBranch']
Encoder        = ['CNN5', 'CNN5Max', 'ResNet50', 'ResNet50Max', 'WideResNet50', 'WideResNet50Max', 'VGG19']
Decoder        = ['BasicDecoder', 'DualDecoder', 'TVADecoder']
Attention      = ['Atten1','Atten2','Atten3','Atten4','Atten5','Atten6','Atten7','Atten8','Atten9','Atten10']
SpatialAttention  = ['MHSA','MHRSA']
CategoryAttention = ['ECAnet']
Control        = ['SumHiddenFeature','BranchesModule']