ImitationModel = ['Basic','Multimodal','Codevilla18','Codevilla19','Kim2017','Experimental','ExpBranch']
Encoder        = ['CNN5', 'ResNet50', 'WideResNet50', 'VGG19']
Decoder        = ['BasicDecoder', 'DualDecoder', 'TVADecoder']
Attention      = ['Atten1','Atten2','Atten3','Atten4','Atten5','Atten6','Atten7','Atten8','Atten9']
Control        = ['SumHiddenFeature','BranchesModule']